i <- c(1)
j <- c(2)
x <- c((10*lambda))
G0G1E <- sparseMatrix(i=i, j=j, x=x, dims=c(1, 2))
i <- c(2)
j <- c(1)
x <- c(Trebuild.dist)
G1G0P0 <- sparseMatrix(i=i, j=j, x=x, dims=c(2, 1))
i <- c(2)
j <- c(1)
x <- c((9*lambda))
G1G1E <- sparseMatrix(i=i, j=j, x=x, dims=c(2, 2))
i <- c(1)
j <- c(2)
x <- c(Trebuild.dist)
G1G1P0 <- sparseMatrix(i=i, j=j, x=x, dims=c(2, 2))
i <- c(1)
j <- c(1)
x <- c((8*lambda))
G1G2E <- sparseMatrix(i=i, j=j, x=x, dims=c(2, 1))
i <- c(1)
j <- c(1)
x <- c(Trecon.dist)
G2G0P1 <- sparseMatrix(i=i, j=j, x=x, dims=c(1, 1))
